#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="trungle8_questcan")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAdsTBx(AdsTBx instance);
  partial void UpdateAdsTBx(AdsTBx instance);
  partial void DeleteAdsTBx(AdsTBx instance);
  partial void InsertUserTypeTBx(UserTypeTBx instance);
  partial void UpdateUserTypeTBx(UserTypeTBx instance);
  partial void DeleteUserTypeTBx(UserTypeTBx instance);
  partial void InsertCategoryTBx(CategoryTBx instance);
  partial void UpdateCategoryTBx(CategoryTBx instance);
  partial void DeleteCategoryTBx(CategoryTBx instance);
  partial void InsertCustomer_Store(Customer_Store instance);
  partial void UpdateCustomer_Store(Customer_Store instance);
  partial void DeleteCustomer_Store(Customer_Store instance);
  partial void InsertDeviceTBx(DeviceTBx instance);
  partial void UpdateDeviceTBx(DeviceTBx instance);
  partial void DeleteDeviceTBx(DeviceTBx instance);
  partial void InsertPageTBx(PageTBx instance);
  partial void UpdatePageTBx(PageTBx instance);
  partial void DeletePageTBx(PageTBx instance);
  partial void InsertPhotoTBx(PhotoTBx instance);
  partial void UpdatePhotoTBx(PhotoTBx instance);
  partial void DeletePhotoTBx(PhotoTBx instance);
  partial void InsertStaff_Store(Staff_Store instance);
  partial void UpdateStaff_Store(Staff_Store instance);
  partial void DeleteStaff_Store(Staff_Store instance);
  partial void InsertStoreTBx(StoreTBx instance);
  partial void UpdateStoreTBx(StoreTBx instance);
  partial void DeleteStoreTBx(StoreTBx instance);
  partial void InsertTaskTBx(TaskTBx instance);
  partial void UpdateTaskTBx(TaskTBx instance);
  partial void DeleteTaskTBx(TaskTBx instance);
  partial void InsertUserTaskTBx(UserTaskTBx instance);
  partial void UpdateUserTaskTBx(UserTaskTBx instance);
  partial void DeleteUserTaskTBx(UserTaskTBx instance);
  partial void InsertUserTBx(UserTBx instance);
  partial void UpdateUserTBx(UserTBx instance);
  partial void DeleteUserTBx(UserTBx instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuestCanConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<AdsTBx> AdsTBxes
	{
		get
		{
			return this.GetTable<AdsTBx>();
		}
	}
	
	public System.Data.Linq.Table<UserTypeTBx> UserTypeTBxes
	{
		get
		{
			return this.GetTable<UserTypeTBx>();
		}
	}
	
	public System.Data.Linq.Table<CategoryTBx> CategoryTBxes
	{
		get
		{
			return this.GetTable<CategoryTBx>();
		}
	}
	
	public System.Data.Linq.Table<Customer_Store> Customer_Stores
	{
		get
		{
			return this.GetTable<Customer_Store>();
		}
	}
	
	public System.Data.Linq.Table<DeviceTBx> DeviceTBxes
	{
		get
		{
			return this.GetTable<DeviceTBx>();
		}
	}
	
	public System.Data.Linq.Table<PageTBx> PageTBxes
	{
		get
		{
			return this.GetTable<PageTBx>();
		}
	}
	
	public System.Data.Linq.Table<PhotoTBx> PhotoTBxes
	{
		get
		{
			return this.GetTable<PhotoTBx>();
		}
	}
	
	public System.Data.Linq.Table<Staff_Store> Staff_Stores
	{
		get
		{
			return this.GetTable<Staff_Store>();
		}
	}
	
	public System.Data.Linq.Table<StoreTBx> StoreTBxes
	{
		get
		{
			return this.GetTable<StoreTBx>();
		}
	}
	
	public System.Data.Linq.Table<TaskTBx> TaskTBxes
	{
		get
		{
			return this.GetTable<TaskTBx>();
		}
	}
	
	public System.Data.Linq.Table<UserTaskTBx> UserTaskTBxes
	{
		get
		{
			return this.GetTable<UserTaskTBx>();
		}
	}
	
	public System.Data.Linq.Table<UserTBx> UserTBxes
	{
		get
		{
			return this.GetTable<UserTBx>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdsTBx")]
public partial class AdsTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _title;
	
	private string _description;
	
	private string _picture;
	
	private string _address;
	
	private string _content;
	
	private System.Nullable<int> _user_id;
	
	private System.Nullable<int> _store_id;
	
	private EntityRef<StoreTBx> _StoreTBx;
	
	private EntityRef<UserTBx> _UserTBx;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnpictureChanging(string value);
    partial void OnpictureChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onstore_idChanging(System.Nullable<int> value);
    partial void Onstore_idChanged();
    #endregion
	
	public AdsTBx()
	{
		this._StoreTBx = default(EntityRef<StoreTBx>);
		this._UserTBx = default(EntityRef<UserTBx>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(100)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture", DbType="NVarChar(100)")]
	public string picture
	{
		get
		{
			return this._picture;
		}
		set
		{
			if ((this._picture != value))
			{
				this.OnpictureChanging(value);
				this.SendPropertyChanging();
				this._picture = value;
				this.SendPropertyChanged("picture");
				this.OnpictureChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(100)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(MAX)")]
	public string content
	{
		get
		{
			return this._content;
		}
		set
		{
			if ((this._content != value))
			{
				this.OncontentChanging(value);
				this.SendPropertyChanging();
				this._content = value;
				this.SendPropertyChanged("content");
				this.OncontentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._UserTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store_id", DbType="Int")]
	public System.Nullable<int> store_id
	{
		get
		{
			return this._store_id;
		}
		set
		{
			if ((this._store_id != value))
			{
				if (this._StoreTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onstore_idChanging(value);
				this.SendPropertyChanging();
				this._store_id = value;
				this.SendPropertyChanged("store_id");
				this.Onstore_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreTBx_AdsTBx", Storage="_StoreTBx", ThisKey="store_id", OtherKey="id", IsForeignKey=true)]
	public StoreTBx StoreTBx
	{
		get
		{
			return this._StoreTBx.Entity;
		}
		set
		{
			StoreTBx previousValue = this._StoreTBx.Entity;
			if (((previousValue != value) 
						|| (this._StoreTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._StoreTBx.Entity = null;
					previousValue.AdsTBxes.Remove(this);
				}
				this._StoreTBx.Entity = value;
				if ((value != null))
				{
					value.AdsTBxes.Add(this);
					this._store_id = value.id;
				}
				else
				{
					this._store_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("StoreTBx");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_AdsTBx", Storage="_UserTBx", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
	public UserTBx UserTBx
	{
		get
		{
			return this._UserTBx.Entity;
		}
		set
		{
			UserTBx previousValue = this._UserTBx.Entity;
			if (((previousValue != value) 
						|| (this._UserTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTBx.Entity = null;
					previousValue.AdsTBxes.Remove(this);
				}
				this._UserTBx.Entity = value;
				if ((value != null))
				{
					value.AdsTBxes.Add(this);
					this._user_id = value.id;
				}
				else
				{
					this._user_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTBx");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTypeTBx")]
public partial class UserTypeTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _name;
	
	private EntitySet<TaskTBx> _TaskTBxes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
	
	public UserTypeTBx()
	{
		this._TaskTBxes = new EntitySet<TaskTBx>(new Action<TaskTBx>(this.attach_TaskTBxes), new Action<TaskTBx>(this.detach_TaskTBxes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTypeTBx_TaskTBx", Storage="_TaskTBxes", ThisKey="id", OtherKey="usertype_id")]
	public EntitySet<TaskTBx> TaskTBxes
	{
		get
		{
			return this._TaskTBxes;
		}
		set
		{
			this._TaskTBxes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TaskTBxes(TaskTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTypeTBx = this;
	}
	
	private void detach_TaskTBxes(TaskTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTypeTBx = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CategoryTBx")]
public partial class CategoryTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _name;
	
	private string _typecategory;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypecategoryChanging(string value);
    partial void OntypecategoryChanged();
    #endregion
	
	public CategoryTBx()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typecategory", DbType="NVarChar(50)")]
	public string typecategory
	{
		get
		{
			return this._typecategory;
		}
		set
		{
			if ((this._typecategory != value))
			{
				this.OntypecategoryChanging(value);
				this.SendPropertyChanging();
				this._typecategory = value;
				this.SendPropertyChanged("typecategory");
				this.OntypecategoryChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer_Store")]
public partial class Customer_Store : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private System.Nullable<int> _user_id;
	
	private System.Nullable<int> _store_id;
	
	private EntityRef<StoreTBx> _StoreTBx;
	
	private EntityRef<UserTBx> _UserTBx;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onstore_idChanging(System.Nullable<int> value);
    partial void Onstore_idChanged();
    #endregion
	
	public Customer_Store()
	{
		this._StoreTBx = default(EntityRef<StoreTBx>);
		this._UserTBx = default(EntityRef<UserTBx>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._UserTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store_id", DbType="Int")]
	public System.Nullable<int> store_id
	{
		get
		{
			return this._store_id;
		}
		set
		{
			if ((this._store_id != value))
			{
				if (this._StoreTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onstore_idChanging(value);
				this.SendPropertyChanging();
				this._store_id = value;
				this.SendPropertyChanged("store_id");
				this.Onstore_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreTBx_Customer_Store", Storage="_StoreTBx", ThisKey="store_id", OtherKey="id", IsForeignKey=true)]
	public StoreTBx StoreTBx
	{
		get
		{
			return this._StoreTBx.Entity;
		}
		set
		{
			StoreTBx previousValue = this._StoreTBx.Entity;
			if (((previousValue != value) 
						|| (this._StoreTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._StoreTBx.Entity = null;
					previousValue.Customer_Stores.Remove(this);
				}
				this._StoreTBx.Entity = value;
				if ((value != null))
				{
					value.Customer_Stores.Add(this);
					this._store_id = value.id;
				}
				else
				{
					this._store_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("StoreTBx");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_Customer_Store", Storage="_UserTBx", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
	public UserTBx UserTBx
	{
		get
		{
			return this._UserTBx.Entity;
		}
		set
		{
			UserTBx previousValue = this._UserTBx.Entity;
			if (((previousValue != value) 
						|| (this._UserTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTBx.Entity = null;
					previousValue.Customer_Stores.Remove(this);
				}
				this._UserTBx.Entity = value;
				if ((value != null))
				{
					value.Customer_Stores.Add(this);
					this._user_id = value.id;
				}
				else
				{
					this._user_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTBx");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceTBx")]
public partial class DeviceTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private System.Nullable<int> _player_id;
	
	private System.Nullable<int> _user_id;
	
	private string _type;
	
	private EntityRef<UserTBx> _UserTBx;
	
	private EntityRef<UserTBx> _UserTBx1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Onplayer_idChanging(System.Nullable<int> value);
    partial void Onplayer_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
	
	public DeviceTBx()
	{
		this._UserTBx = default(EntityRef<UserTBx>);
		this._UserTBx1 = default(EntityRef<UserTBx>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_player_id", DbType="Int")]
	public System.Nullable<int> player_id
	{
		get
		{
			return this._player_id;
		}
		set
		{
			if ((this._player_id != value))
			{
				this.Onplayer_idChanging(value);
				this.SendPropertyChanging();
				this._player_id = value;
				this.SendPropertyChanged("player_id");
				this.Onplayer_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if ((this._UserTBx.HasLoadedOrAssignedValue || this._UserTBx1.HasLoadedOrAssignedValue))
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_DeviceTBx", Storage="_UserTBx", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
	public UserTBx UserTBx
	{
		get
		{
			return this._UserTBx.Entity;
		}
		set
		{
			UserTBx previousValue = this._UserTBx.Entity;
			if (((previousValue != value) 
						|| (this._UserTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTBx.Entity = null;
					previousValue.DeviceTBxes.Remove(this);
				}
				this._UserTBx.Entity = value;
				if ((value != null))
				{
					value.DeviceTBxes.Add(this);
					this._user_id = value.id;
				}
				else
				{
					this._user_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTBx");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_DeviceTBx1", Storage="_UserTBx1", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
	public UserTBx UserTBx1
	{
		get
		{
			return this._UserTBx1.Entity;
		}
		set
		{
			UserTBx previousValue = this._UserTBx1.Entity;
			if (((previousValue != value) 
						|| (this._UserTBx1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTBx1.Entity = null;
					previousValue.DeviceTBxes1.Remove(this);
				}
				this._UserTBx1.Entity = value;
				if ((value != null))
				{
					value.DeviceTBxes1.Add(this);
					this._user_id = value.id;
				}
				else
				{
					this._user_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTBx1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PageTBx")]
public partial class PageTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _title;
	
	private string _description;
	
	private string _create_day;
	
	private string _picture;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Oncreate_dayChanging(string value);
    partial void Oncreate_dayChanged();
    partial void OnpictureChanging(string value);
    partial void OnpictureChanged();
    #endregion
	
	public PageTBx()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(200)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_day", DbType="NVarChar(50)")]
	public string create_day
	{
		get
		{
			return this._create_day;
		}
		set
		{
			if ((this._create_day != value))
			{
				this.Oncreate_dayChanging(value);
				this.SendPropertyChanging();
				this._create_day = value;
				this.SendPropertyChanged("create_day");
				this.Oncreate_dayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture", DbType="NVarChar(MAX)")]
	public string picture
	{
		get
		{
			return this._picture;
		}
		set
		{
			if ((this._picture != value))
			{
				this.OnpictureChanging(value);
				this.SendPropertyChanging();
				this._picture = value;
				this.SendPropertyChanged("picture");
				this.OnpictureChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhotoTBx")]
public partial class PhotoTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _create_day;
	
	private System.Nullable<int> _id_user;
	
	private System.Nullable<int> _id_store;
	
	private string _name;
	
	private string _lat;
	
	private string _long;
	
	private EntityRef<StoreTBx> _StoreTBx;
	
	private EntityRef<UserTBx> _UserTBx;
	
	private EntityRef<UserTBx> _UserTBx1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Oncreate_dayChanging(string value);
    partial void Oncreate_dayChanged();
    partial void Onid_userChanging(System.Nullable<int> value);
    partial void Onid_userChanged();
    partial void Onid_storeChanging(System.Nullable<int> value);
    partial void Onid_storeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnlatChanging(string value);
    partial void OnlatChanged();
    partial void OnlongChanging(string value);
    partial void OnlongChanged();
    #endregion
	
	public PhotoTBx()
	{
		this._StoreTBx = default(EntityRef<StoreTBx>);
		this._UserTBx = default(EntityRef<UserTBx>);
		this._UserTBx1 = default(EntityRef<UserTBx>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_day", DbType="NVarChar(50)")]
	public string create_day
	{
		get
		{
			return this._create_day;
		}
		set
		{
			if ((this._create_day != value))
			{
				this.Oncreate_dayChanging(value);
				this.SendPropertyChanging();
				this._create_day = value;
				this.SendPropertyChanged("create_day");
				this.Oncreate_dayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int")]
	public System.Nullable<int> id_user
	{
		get
		{
			return this._id_user;
		}
		set
		{
			if ((this._id_user != value))
			{
				if ((this._UserTBx.HasLoadedOrAssignedValue || this._UserTBx1.HasLoadedOrAssignedValue))
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_userChanging(value);
				this.SendPropertyChanging();
				this._id_user = value;
				this.SendPropertyChanged("id_user");
				this.Onid_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_store", DbType="Int")]
	public System.Nullable<int> id_store
	{
		get
		{
			return this._id_store;
		}
		set
		{
			if ((this._id_store != value))
			{
				if (this._StoreTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_storeChanging(value);
				this.SendPropertyChanging();
				this._id_store = value;
				this.SendPropertyChanged("id_store");
				this.Onid_storeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="NVarChar(100)")]
	public string lat
	{
		get
		{
			return this._lat;
		}
		set
		{
			if ((this._lat != value))
			{
				this.OnlatChanging(value);
				this.SendPropertyChanging();
				this._lat = value;
				this.SendPropertyChanged("lat");
				this.OnlatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="long", Storage="_long", DbType="NVarChar(100)")]
	public string @long
	{
		get
		{
			return this._long;
		}
		set
		{
			if ((this._long != value))
			{
				this.OnlongChanging(value);
				this.SendPropertyChanging();
				this._long = value;
				this.SendPropertyChanged("@long");
				this.OnlongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreTBx_PhotoTBx", Storage="_StoreTBx", ThisKey="id_store", OtherKey="id", IsForeignKey=true)]
	public StoreTBx StoreTBx
	{
		get
		{
			return this._StoreTBx.Entity;
		}
		set
		{
			StoreTBx previousValue = this._StoreTBx.Entity;
			if (((previousValue != value) 
						|| (this._StoreTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._StoreTBx.Entity = null;
					previousValue.PhotoTBxes.Remove(this);
				}
				this._StoreTBx.Entity = value;
				if ((value != null))
				{
					value.PhotoTBxes.Add(this);
					this._id_store = value.id;
				}
				else
				{
					this._id_store = default(Nullable<int>);
				}
				this.SendPropertyChanged("StoreTBx");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_PhotoTBx", Storage="_UserTBx", ThisKey="id_user", OtherKey="id", IsForeignKey=true)]
	public UserTBx UserTBx
	{
		get
		{
			return this._UserTBx.Entity;
		}
		set
		{
			UserTBx previousValue = this._UserTBx.Entity;
			if (((previousValue != value) 
						|| (this._UserTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTBx.Entity = null;
					previousValue.PhotoTBxes.Remove(this);
				}
				this._UserTBx.Entity = value;
				if ((value != null))
				{
					value.PhotoTBxes.Add(this);
					this._id_user = value.id;
				}
				else
				{
					this._id_user = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTBx");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_PhotoTBx1", Storage="_UserTBx1", ThisKey="id_user", OtherKey="id", IsForeignKey=true)]
	public UserTBx UserTBx1
	{
		get
		{
			return this._UserTBx1.Entity;
		}
		set
		{
			UserTBx previousValue = this._UserTBx1.Entity;
			if (((previousValue != value) 
						|| (this._UserTBx1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTBx1.Entity = null;
					previousValue.PhotoTBxes1.Remove(this);
				}
				this._UserTBx1.Entity = value;
				if ((value != null))
				{
					value.PhotoTBxes1.Add(this);
					this._id_user = value.id;
				}
				else
				{
					this._id_user = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTBx1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Staff_Store")]
public partial class Staff_Store : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private System.Nullable<int> _user_id;
	
	private System.Nullable<int> _store_id;
	
	private EntityRef<StoreTBx> _StoreTBx;
	
	private EntityRef<UserTBx> _UserTBx;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onstore_idChanging(System.Nullable<int> value);
    partial void Onstore_idChanged();
    #endregion
	
	public Staff_Store()
	{
		this._StoreTBx = default(EntityRef<StoreTBx>);
		this._UserTBx = default(EntityRef<UserTBx>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._UserTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store_id", DbType="Int")]
	public System.Nullable<int> store_id
	{
		get
		{
			return this._store_id;
		}
		set
		{
			if ((this._store_id != value))
			{
				if (this._StoreTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onstore_idChanging(value);
				this.SendPropertyChanging();
				this._store_id = value;
				this.SendPropertyChanged("store_id");
				this.Onstore_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreTBx_Staff_Store", Storage="_StoreTBx", ThisKey="store_id", OtherKey="id", IsForeignKey=true)]
	public StoreTBx StoreTBx
	{
		get
		{
			return this._StoreTBx.Entity;
		}
		set
		{
			StoreTBx previousValue = this._StoreTBx.Entity;
			if (((previousValue != value) 
						|| (this._StoreTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._StoreTBx.Entity = null;
					previousValue.Staff_Stores.Remove(this);
				}
				this._StoreTBx.Entity = value;
				if ((value != null))
				{
					value.Staff_Stores.Add(this);
					this._store_id = value.id;
				}
				else
				{
					this._store_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("StoreTBx");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_Staff_Store", Storage="_UserTBx", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
	public UserTBx UserTBx
	{
		get
		{
			return this._UserTBx.Entity;
		}
		set
		{
			UserTBx previousValue = this._UserTBx.Entity;
			if (((previousValue != value) 
						|| (this._UserTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTBx.Entity = null;
					previousValue.Staff_Stores.Remove(this);
				}
				this._UserTBx.Entity = value;
				if ((value != null))
				{
					value.Staff_Stores.Add(this);
					this._user_id = value.id;
				}
				else
				{
					this._user_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTBx");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoreTBx")]
public partial class StoreTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _name;
	
	private string _address;
	
	private string _email;
	
	private string _phone;
	
	private string _open_time;
	
	private string _close_time;
	
	private string _lat;
	
	private string _long;
	
	private EntitySet<AdsTBx> _AdsTBxes;
	
	private EntitySet<Customer_Store> _Customer_Stores;
	
	private EntitySet<PhotoTBx> _PhotoTBxes;
	
	private EntitySet<Staff_Store> _Staff_Stores;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onopen_timeChanging(string value);
    partial void Onopen_timeChanged();
    partial void Onclose_timeChanging(string value);
    partial void Onclose_timeChanged();
    partial void OnlatChanging(string value);
    partial void OnlatChanged();
    partial void OnlongChanging(string value);
    partial void OnlongChanged();
    #endregion
	
	public StoreTBx()
	{
		this._AdsTBxes = new EntitySet<AdsTBx>(new Action<AdsTBx>(this.attach_AdsTBxes), new Action<AdsTBx>(this.detach_AdsTBxes));
		this._Customer_Stores = new EntitySet<Customer_Store>(new Action<Customer_Store>(this.attach_Customer_Stores), new Action<Customer_Store>(this.detach_Customer_Stores));
		this._PhotoTBxes = new EntitySet<PhotoTBx>(new Action<PhotoTBx>(this.attach_PhotoTBxes), new Action<PhotoTBx>(this.detach_PhotoTBxes));
		this._Staff_Stores = new EntitySet<Staff_Store>(new Action<Staff_Store>(this.attach_Staff_Stores), new Action<Staff_Store>(this.detach_Staff_Stores));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_open_time", DbType="NVarChar(50)")]
	public string open_time
	{
		get
		{
			return this._open_time;
		}
		set
		{
			if ((this._open_time != value))
			{
				this.Onopen_timeChanging(value);
				this.SendPropertyChanging();
				this._open_time = value;
				this.SendPropertyChanged("open_time");
				this.Onopen_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_close_time", DbType="NVarChar(50)")]
	public string close_time
	{
		get
		{
			return this._close_time;
		}
		set
		{
			if ((this._close_time != value))
			{
				this.Onclose_timeChanging(value);
				this.SendPropertyChanging();
				this._close_time = value;
				this.SendPropertyChanged("close_time");
				this.Onclose_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="NVarChar(50)")]
	public string lat
	{
		get
		{
			return this._lat;
		}
		set
		{
			if ((this._lat != value))
			{
				this.OnlatChanging(value);
				this.SendPropertyChanging();
				this._lat = value;
				this.SendPropertyChanged("lat");
				this.OnlatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="long", Storage="_long", DbType="NVarChar(50)")]
	public string @long
	{
		get
		{
			return this._long;
		}
		set
		{
			if ((this._long != value))
			{
				this.OnlongChanging(value);
				this.SendPropertyChanging();
				this._long = value;
				this.SendPropertyChanged("@long");
				this.OnlongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreTBx_AdsTBx", Storage="_AdsTBxes", ThisKey="id", OtherKey="store_id")]
	public EntitySet<AdsTBx> AdsTBxes
	{
		get
		{
			return this._AdsTBxes;
		}
		set
		{
			this._AdsTBxes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreTBx_Customer_Store", Storage="_Customer_Stores", ThisKey="id", OtherKey="store_id")]
	public EntitySet<Customer_Store> Customer_Stores
	{
		get
		{
			return this._Customer_Stores;
		}
		set
		{
			this._Customer_Stores.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreTBx_PhotoTBx", Storage="_PhotoTBxes", ThisKey="id", OtherKey="id_store")]
	public EntitySet<PhotoTBx> PhotoTBxes
	{
		get
		{
			return this._PhotoTBxes;
		}
		set
		{
			this._PhotoTBxes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StoreTBx_Staff_Store", Storage="_Staff_Stores", ThisKey="id", OtherKey="store_id")]
	public EntitySet<Staff_Store> Staff_Stores
	{
		get
		{
			return this._Staff_Stores;
		}
		set
		{
			this._Staff_Stores.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_AdsTBxes(AdsTBx entity)
	{
		this.SendPropertyChanging();
		entity.StoreTBx = this;
	}
	
	private void detach_AdsTBxes(AdsTBx entity)
	{
		this.SendPropertyChanging();
		entity.StoreTBx = null;
	}
	
	private void attach_Customer_Stores(Customer_Store entity)
	{
		this.SendPropertyChanging();
		entity.StoreTBx = this;
	}
	
	private void detach_Customer_Stores(Customer_Store entity)
	{
		this.SendPropertyChanging();
		entity.StoreTBx = null;
	}
	
	private void attach_PhotoTBxes(PhotoTBx entity)
	{
		this.SendPropertyChanging();
		entity.StoreTBx = this;
	}
	
	private void detach_PhotoTBxes(PhotoTBx entity)
	{
		this.SendPropertyChanging();
		entity.StoreTBx = null;
	}
	
	private void attach_Staff_Stores(Staff_Store entity)
	{
		this.SendPropertyChanging();
		entity.StoreTBx = this;
	}
	
	private void detach_Staff_Stores(Staff_Store entity)
	{
		this.SendPropertyChanging();
		entity.StoreTBx = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaskTBx")]
public partial class TaskTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _title;
	
	private string _description;
	
	private int _point;
	
	private string _start_time;
	
	private string _end_time;
	
	private System.Nullable<int> _usertype_id;
	
	private string _content;
	
	private string _lat;
	
	private string _long;
	
	private EntitySet<UserTaskTBx> _UserTaskTBxes;
	
	private EntityRef<UserTypeTBx> _UserTypeTBx;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnpointChanging(int value);
    partial void OnpointChanged();
    partial void Onstart_timeChanging(string value);
    partial void Onstart_timeChanged();
    partial void Onend_timeChanging(string value);
    partial void Onend_timeChanged();
    partial void Onusertype_idChanging(System.Nullable<int> value);
    partial void Onusertype_idChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OnlatChanging(string value);
    partial void OnlatChanged();
    partial void OnlongChanging(string value);
    partial void OnlongChanged();
    #endregion
	
	public TaskTBx()
	{
		this._UserTaskTBxes = new EntitySet<UserTaskTBx>(new Action<UserTaskTBx>(this.attach_UserTaskTBxes), new Action<UserTaskTBx>(this.detach_UserTaskTBxes));
		this._UserTypeTBx = default(EntityRef<UserTypeTBx>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(200)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_point", DbType="Int NOT NULL")]
	public int point
	{
		get
		{
			return this._point;
		}
		set
		{
			if ((this._point != value))
			{
				this.OnpointChanging(value);
				this.SendPropertyChanging();
				this._point = value;
				this.SendPropertyChanged("point");
				this.OnpointChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="NVarChar(50)")]
	public string start_time
	{
		get
		{
			return this._start_time;
		}
		set
		{
			if ((this._start_time != value))
			{
				this.Onstart_timeChanging(value);
				this.SendPropertyChanging();
				this._start_time = value;
				this.SendPropertyChanged("start_time");
				this.Onstart_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="NVarChar(50)")]
	public string end_time
	{
		get
		{
			return this._end_time;
		}
		set
		{
			if ((this._end_time != value))
			{
				this.Onend_timeChanging(value);
				this.SendPropertyChanging();
				this._end_time = value;
				this.SendPropertyChanged("end_time");
				this.Onend_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype_id", DbType="Int")]
	public System.Nullable<int> usertype_id
	{
		get
		{
			return this._usertype_id;
		}
		set
		{
			if ((this._usertype_id != value))
			{
				if (this._UserTypeTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onusertype_idChanging(value);
				this.SendPropertyChanging();
				this._usertype_id = value;
				this.SendPropertyChanged("usertype_id");
				this.Onusertype_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(MAX)")]
	public string content
	{
		get
		{
			return this._content;
		}
		set
		{
			if ((this._content != value))
			{
				this.OncontentChanging(value);
				this.SendPropertyChanging();
				this._content = value;
				this.SendPropertyChanged("content");
				this.OncontentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="NVarChar(200)")]
	public string lat
	{
		get
		{
			return this._lat;
		}
		set
		{
			if ((this._lat != value))
			{
				this.OnlatChanging(value);
				this.SendPropertyChanging();
				this._lat = value;
				this.SendPropertyChanged("lat");
				this.OnlatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="long", Storage="_long", DbType="NVarChar(2000)")]
	public string @long
	{
		get
		{
			return this._long;
		}
		set
		{
			if ((this._long != value))
			{
				this.OnlongChanging(value);
				this.SendPropertyChanging();
				this._long = value;
				this.SendPropertyChanged("@long");
				this.OnlongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaskTBx_UserTaskTBx", Storage="_UserTaskTBxes", ThisKey="id", OtherKey="task_id")]
	public EntitySet<UserTaskTBx> UserTaskTBxes
	{
		get
		{
			return this._UserTaskTBxes;
		}
		set
		{
			this._UserTaskTBxes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTypeTBx_TaskTBx", Storage="_UserTypeTBx", ThisKey="usertype_id", OtherKey="id", IsForeignKey=true)]
	public UserTypeTBx UserTypeTBx
	{
		get
		{
			return this._UserTypeTBx.Entity;
		}
		set
		{
			UserTypeTBx previousValue = this._UserTypeTBx.Entity;
			if (((previousValue != value) 
						|| (this._UserTypeTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTypeTBx.Entity = null;
					previousValue.TaskTBxes.Remove(this);
				}
				this._UserTypeTBx.Entity = value;
				if ((value != null))
				{
					value.TaskTBxes.Add(this);
					this._usertype_id = value.id;
				}
				else
				{
					this._usertype_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTypeTBx");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_UserTaskTBxes(UserTaskTBx entity)
	{
		this.SendPropertyChanging();
		entity.TaskTBx = this;
	}
	
	private void detach_UserTaskTBxes(UserTaskTBx entity)
	{
		this.SendPropertyChanging();
		entity.TaskTBx = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTaskTBx")]
public partial class UserTaskTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private System.Nullable<int> _task_id;
	
	private System.Nullable<int> _user_id;
	
	private EntityRef<TaskTBx> _TaskTBx;
	
	private EntityRef<UserTBx> _UserTBx;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Ontask_idChanging(System.Nullable<int> value);
    partial void Ontask_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    #endregion
	
	public UserTaskTBx()
	{
		this._TaskTBx = default(EntityRef<TaskTBx>);
		this._UserTBx = default(EntityRef<UserTBx>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_id", DbType="Int")]
	public System.Nullable<int> task_id
	{
		get
		{
			return this._task_id;
		}
		set
		{
			if ((this._task_id != value))
			{
				if (this._TaskTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ontask_idChanging(value);
				this.SendPropertyChanging();
				this._task_id = value;
				this.SendPropertyChanged("task_id");
				this.Ontask_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				if (this._UserTBx.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaskTBx_UserTaskTBx", Storage="_TaskTBx", ThisKey="task_id", OtherKey="id", IsForeignKey=true)]
	public TaskTBx TaskTBx
	{
		get
		{
			return this._TaskTBx.Entity;
		}
		set
		{
			TaskTBx previousValue = this._TaskTBx.Entity;
			if (((previousValue != value) 
						|| (this._TaskTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TaskTBx.Entity = null;
					previousValue.UserTaskTBxes.Remove(this);
				}
				this._TaskTBx.Entity = value;
				if ((value != null))
				{
					value.UserTaskTBxes.Add(this);
					this._task_id = value.id;
				}
				else
				{
					this._task_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("TaskTBx");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_UserTaskTBx", Storage="_UserTBx", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
	public UserTBx UserTBx
	{
		get
		{
			return this._UserTBx.Entity;
		}
		set
		{
			UserTBx previousValue = this._UserTBx.Entity;
			if (((previousValue != value) 
						|| (this._UserTBx.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._UserTBx.Entity = null;
					previousValue.UserTaskTBxes.Remove(this);
				}
				this._UserTBx.Entity = value;
				if ((value != null))
				{
					value.UserTaskTBxes.Add(this);
					this._user_id = value.id;
				}
				else
				{
					this._user_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("UserTBx");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTBx")]
public partial class UserTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _first_name;
	
	private string _last_name;
	
	private string _full_name;
	
	private string _email;
	
	private string _phone;
	
	private string _birthday;
	
	private string _create_day;
	
	private string _last_loginday;
	
	private string _token;
	
	private string _address;
	
	private string _password;
	
	private System.Nullable<int> _credit;
	
	private System.Nullable<int> _typeuser_id;
	
	private EntitySet<AdsTBx> _AdsTBxes;
	
	private EntitySet<Customer_Store> _Customer_Stores;
	
	private EntitySet<DeviceTBx> _DeviceTBxes;
	
	private EntitySet<DeviceTBx> _DeviceTBxes1;
	
	private EntitySet<PhotoTBx> _PhotoTBxes;
	
	private EntitySet<PhotoTBx> _PhotoTBxes1;
	
	private EntitySet<Staff_Store> _Staff_Stores;
	
	private EntitySet<UserTaskTBx> _UserTaskTBxes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnbirthdayChanging(string value);
    partial void OnbirthdayChanged();
    partial void Oncreate_dayChanging(string value);
    partial void Oncreate_dayChanged();
    partial void Onlast_logindayChanging(string value);
    partial void Onlast_logindayChanged();
    partial void OntokenChanging(string value);
    partial void OntokenChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OncreditChanging(System.Nullable<int> value);
    partial void OncreditChanged();
    partial void Ontypeuser_idChanging(System.Nullable<int> value);
    partial void Ontypeuser_idChanged();
    #endregion
	
	public UserTBx()
	{
		this._AdsTBxes = new EntitySet<AdsTBx>(new Action<AdsTBx>(this.attach_AdsTBxes), new Action<AdsTBx>(this.detach_AdsTBxes));
		this._Customer_Stores = new EntitySet<Customer_Store>(new Action<Customer_Store>(this.attach_Customer_Stores), new Action<Customer_Store>(this.detach_Customer_Stores));
		this._DeviceTBxes = new EntitySet<DeviceTBx>(new Action<DeviceTBx>(this.attach_DeviceTBxes), new Action<DeviceTBx>(this.detach_DeviceTBxes));
		this._DeviceTBxes1 = new EntitySet<DeviceTBx>(new Action<DeviceTBx>(this.attach_DeviceTBxes1), new Action<DeviceTBx>(this.detach_DeviceTBxes1));
		this._PhotoTBxes = new EntitySet<PhotoTBx>(new Action<PhotoTBx>(this.attach_PhotoTBxes), new Action<PhotoTBx>(this.detach_PhotoTBxes));
		this._PhotoTBxes1 = new EntitySet<PhotoTBx>(new Action<PhotoTBx>(this.attach_PhotoTBxes1), new Action<PhotoTBx>(this.detach_PhotoTBxes1));
		this._Staff_Stores = new EntitySet<Staff_Store>(new Action<Staff_Store>(this.attach_Staff_Stores), new Action<Staff_Store>(this.detach_Staff_Stores));
		this._UserTaskTBxes = new EntitySet<UserTaskTBx>(new Action<UserTaskTBx>(this.attach_UserTaskTBxes), new Action<UserTaskTBx>(this.detach_UserTaskTBxes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(50)")]
	public string first_name
	{
		get
		{
			return this._first_name;
		}
		set
		{
			if ((this._first_name != value))
			{
				this.Onfirst_nameChanging(value);
				this.SendPropertyChanging();
				this._first_name = value;
				this.SendPropertyChanged("first_name");
				this.Onfirst_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50)")]
	public string last_name
	{
		get
		{
			return this._last_name;
		}
		set
		{
			if ((this._last_name != value))
			{
				this.Onlast_nameChanging(value);
				this.SendPropertyChanging();
				this._last_name = value;
				this.SendPropertyChanged("last_name");
				this.Onlast_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="NVarChar(100)")]
	public string full_name
	{
		get
		{
			return this._full_name;
		}
		set
		{
			if ((this._full_name != value))
			{
				this.Onfull_nameChanging(value);
				this.SendPropertyChanging();
				this._full_name = value;
				this.SendPropertyChanged("full_name");
				this.Onfull_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(50)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="NVarChar(50)")]
	public string birthday
	{
		get
		{
			return this._birthday;
		}
		set
		{
			if ((this._birthday != value))
			{
				this.OnbirthdayChanging(value);
				this.SendPropertyChanging();
				this._birthday = value;
				this.SendPropertyChanged("birthday");
				this.OnbirthdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_day", DbType="NVarChar(50)")]
	public string create_day
	{
		get
		{
			return this._create_day;
		}
		set
		{
			if ((this._create_day != value))
			{
				this.Oncreate_dayChanging(value);
				this.SendPropertyChanging();
				this._create_day = value;
				this.SendPropertyChanged("create_day");
				this.Oncreate_dayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_loginday", DbType="NVarChar(50)")]
	public string last_loginday
	{
		get
		{
			return this._last_loginday;
		}
		set
		{
			if ((this._last_loginday != value))
			{
				this.Onlast_logindayChanging(value);
				this.SendPropertyChanging();
				this._last_loginday = value;
				this.SendPropertyChanged("last_loginday");
				this.Onlast_logindayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="NVarChar(50)")]
	public string token
	{
		get
		{
			return this._token;
		}
		set
		{
			if ((this._token != value))
			{
				this.OntokenChanging(value);
				this.SendPropertyChanging();
				this._token = value;
				this.SendPropertyChanged("token");
				this.OntokenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(200)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_credit", DbType="Int")]
	public System.Nullable<int> credit
	{
		get
		{
			return this._credit;
		}
		set
		{
			if ((this._credit != value))
			{
				this.OncreditChanging(value);
				this.SendPropertyChanging();
				this._credit = value;
				this.SendPropertyChanged("credit");
				this.OncreditChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeuser_id", DbType="Int")]
	public System.Nullable<int> typeuser_id
	{
		get
		{
			return this._typeuser_id;
		}
		set
		{
			if ((this._typeuser_id != value))
			{
				this.Ontypeuser_idChanging(value);
				this.SendPropertyChanging();
				this._typeuser_id = value;
				this.SendPropertyChanged("typeuser_id");
				this.Ontypeuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_AdsTBx", Storage="_AdsTBxes", ThisKey="id", OtherKey="user_id")]
	public EntitySet<AdsTBx> AdsTBxes
	{
		get
		{
			return this._AdsTBxes;
		}
		set
		{
			this._AdsTBxes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_Customer_Store", Storage="_Customer_Stores", ThisKey="id", OtherKey="user_id")]
	public EntitySet<Customer_Store> Customer_Stores
	{
		get
		{
			return this._Customer_Stores;
		}
		set
		{
			this._Customer_Stores.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_DeviceTBx", Storage="_DeviceTBxes", ThisKey="id", OtherKey="user_id")]
	public EntitySet<DeviceTBx> DeviceTBxes
	{
		get
		{
			return this._DeviceTBxes;
		}
		set
		{
			this._DeviceTBxes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_DeviceTBx1", Storage="_DeviceTBxes1", ThisKey="id", OtherKey="user_id")]
	public EntitySet<DeviceTBx> DeviceTBxes1
	{
		get
		{
			return this._DeviceTBxes1;
		}
		set
		{
			this._DeviceTBxes1.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_PhotoTBx", Storage="_PhotoTBxes", ThisKey="id", OtherKey="id_user")]
	public EntitySet<PhotoTBx> PhotoTBxes
	{
		get
		{
			return this._PhotoTBxes;
		}
		set
		{
			this._PhotoTBxes.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_PhotoTBx1", Storage="_PhotoTBxes1", ThisKey="id", OtherKey="id_user")]
	public EntitySet<PhotoTBx> PhotoTBxes1
	{
		get
		{
			return this._PhotoTBxes1;
		}
		set
		{
			this._PhotoTBxes1.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_Staff_Store", Storage="_Staff_Stores", ThisKey="id", OtherKey="user_id")]
	public EntitySet<Staff_Store> Staff_Stores
	{
		get
		{
			return this._Staff_Stores;
		}
		set
		{
			this._Staff_Stores.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserTBx_UserTaskTBx", Storage="_UserTaskTBxes", ThisKey="id", OtherKey="user_id")]
	public EntitySet<UserTaskTBx> UserTaskTBxes
	{
		get
		{
			return this._UserTaskTBxes;
		}
		set
		{
			this._UserTaskTBxes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_AdsTBxes(AdsTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = this;
	}
	
	private void detach_AdsTBxes(AdsTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = null;
	}
	
	private void attach_Customer_Stores(Customer_Store entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = this;
	}
	
	private void detach_Customer_Stores(Customer_Store entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = null;
	}
	
	private void attach_DeviceTBxes(DeviceTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = this;
	}
	
	private void detach_DeviceTBxes(DeviceTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = null;
	}
	
	private void attach_DeviceTBxes1(DeviceTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx1 = this;
	}
	
	private void detach_DeviceTBxes1(DeviceTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx1 = null;
	}
	
	private void attach_PhotoTBxes(PhotoTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = this;
	}
	
	private void detach_PhotoTBxes(PhotoTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = null;
	}
	
	private void attach_PhotoTBxes1(PhotoTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx1 = this;
	}
	
	private void detach_PhotoTBxes1(PhotoTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx1 = null;
	}
	
	private void attach_Staff_Stores(Staff_Store entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = this;
	}
	
	private void detach_Staff_Stores(Staff_Store entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = null;
	}
	
	private void attach_UserTaskTBxes(UserTaskTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = this;
	}
	
	private void detach_UserTaskTBxes(UserTaskTBx entity)
	{
		this.SendPropertyChanging();
		entity.UserTBx = null;
	}
}
#pragma warning restore 1591
