#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="trungle8_fundice")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertPlayerTBx(PlayerTBx instance);
  partial void UpdatePlayerTBx(PlayerTBx instance);
  partial void DeletePlayerTBx(PlayerTBx instance);
  partial void InsertRollHistoryTBx(RollHistoryTBx instance);
  partial void UpdateRollHistoryTBx(RollHistoryTBx instance);
  partial void DeleteRollHistoryTBx(RollHistoryTBx instance);
  partial void InsertStepTBx(StepTBx instance);
  partial void UpdateStepTBx(StepTBx instance);
  partial void DeleteStepTBx(StepTBx instance);
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["trungle8_fundiceConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<PlayerTBx> PlayerTBxes
	{
		get
		{
			return this.GetTable<PlayerTBx>();
		}
	}
	
	public System.Data.Linq.Table<RollHistoryTBx> RollHistoryTBxes
	{
		get
		{
			return this.GetTable<RollHistoryTBx>();
		}
	}
	
	public System.Data.Linq.Table<StepTBx> StepTBxes
	{
		get
		{
			return this.GetTable<StepTBx>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PlayerTBx")]
public partial class PlayerTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private string _name;
	
	private System.Nullable<int> _dice;
	
	private string _total_step;
	
	private System.Nullable<int> _curent_step;
	
	private System.Nullable<int> _user_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndiceChanging(System.Nullable<int> value);
    partial void OndiceChanged();
    partial void Ontotal_stepChanging(string value);
    partial void Ontotal_stepChanged();
    partial void Oncurent_stepChanging(System.Nullable<int> value);
    partial void Oncurent_stepChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    #endregion
	
	public PlayerTBx()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dice", DbType="Int")]
	public System.Nullable<int> dice
	{
		get
		{
			return this._dice;
		}
		set
		{
			if ((this._dice != value))
			{
				this.OndiceChanging(value);
				this.SendPropertyChanging();
				this._dice = value;
				this.SendPropertyChanged("dice");
				this.OndiceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_step", DbType="NVarChar(50)")]
	public string total_step
	{
		get
		{
			return this._total_step;
		}
		set
		{
			if ((this._total_step != value))
			{
				this.Ontotal_stepChanging(value);
				this.SendPropertyChanging();
				this._total_step = value;
				this.SendPropertyChanged("total_step");
				this.Ontotal_stepChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curent_step", DbType="Int")]
	public System.Nullable<int> curent_step
	{
		get
		{
			return this._curent_step;
		}
		set
		{
			if ((this._curent_step != value))
			{
				this.Oncurent_stepChanging(value);
				this.SendPropertyChanging();
				this._curent_step = value;
				this.SendPropertyChanged("curent_step");
				this.Oncurent_stepChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RollHistoryTBx")]
public partial class RollHistoryTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private System.Nullable<int> _dice_point;
	
	private System.Nullable<int> _start_step;
	
	private System.Nullable<int> _end_step;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Ondice_pointChanging(System.Nullable<int> value);
    partial void Ondice_pointChanged();
    partial void Onstart_stepChanging(System.Nullable<int> value);
    partial void Onstart_stepChanged();
    partial void Onend_stepChanging(System.Nullable<int> value);
    partial void Onend_stepChanged();
    #endregion
	
	public RollHistoryTBx()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dice_point", DbType="Int")]
	public System.Nullable<int> dice_point
	{
		get
		{
			return this._dice_point;
		}
		set
		{
			if ((this._dice_point != value))
			{
				this.Ondice_pointChanging(value);
				this.SendPropertyChanging();
				this._dice_point = value;
				this.SendPropertyChanged("dice_point");
				this.Ondice_pointChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_step", DbType="Int")]
	public System.Nullable<int> start_step
	{
		get
		{
			return this._start_step;
		}
		set
		{
			if ((this._start_step != value))
			{
				this.Onstart_stepChanging(value);
				this.SendPropertyChanging();
				this._start_step = value;
				this.SendPropertyChanged("start_step");
				this.Onstart_stepChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_step", DbType="Int")]
	public System.Nullable<int> end_step
	{
		get
		{
			return this._end_step;
		}
		set
		{
			if ((this._end_step != value))
			{
				this.Onend_stepChanging(value);
				this.SendPropertyChanging();
				this._end_step = value;
				this.SendPropertyChanged("end_step");
				this.Onend_stepChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StepTBx")]
public partial class StepTBx : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _status;
	
	private int _step_number;
	
	private string _effect;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Onstep_numberChanging(int value);
    partial void Onstep_numberChanged();
    partial void OneffectChanging(string value);
    partial void OneffectChanged();
    #endregion
	
	public StepTBx()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step_number", DbType="Int NOT NULL")]
	public int step_number
	{
		get
		{
			return this._step_number;
		}
		set
		{
			if ((this._step_number != value))
			{
				this.Onstep_numberChanging(value);
				this.SendPropertyChanging();
				this._step_number = value;
				this.SendPropertyChanged("step_number");
				this.Onstep_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effect", DbType="NVarChar(50)")]
	public string effect
	{
		get
		{
			return this._effect;
		}
		set
		{
			if ((this._effect != value))
			{
				this.OneffectChanging(value);
				this.SendPropertyChanging();
				this._effect = value;
				this.SendPropertyChanged("effect");
				this.OneffectChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
